services:
  - type: web
    name: chanforum
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: SECRET_KEY
        sync: false
    plan: free
